// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpfJiPZfvkzSAmmIAQdxMSHCgmX5JtEa0',
    appId: '1:813058254079:web:dccf4907bf8069377858ca',
    messagingSenderId: '813058254079',
    projectId: 'lib-management-8913c',
    authDomain: 'lib-management-8913c.firebaseapp.com',
    storageBucket: 'lib-management-8913c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2toEjqQgrFhL6iiTY7JHg0mV9EEcsUkk',
    appId: '1:813058254079:android:fdcf90706f2374ea7858ca',
    messagingSenderId: '813058254079',
    projectId: 'lib-management-8913c',
    storageBucket: 'lib-management-8913c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQlkSEe8xpEQhCncYa25nbl_8PJV0oAdw',
    appId: '1:813058254079:ios:118947ca65d956ea7858ca',
    messagingSenderId: '813058254079',
    projectId: 'lib-management-8913c',
    storageBucket: 'lib-management-8913c.appspot.com',
    iosBundleId: 'com.example.libManage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQlkSEe8xpEQhCncYa25nbl_8PJV0oAdw',
    appId: '1:813058254079:ios:368141479f0aaef27858ca',
    messagingSenderId: '813058254079',
    projectId: 'lib-management-8913c',
    storageBucket: 'lib-management-8913c.appspot.com',
    iosBundleId: 'com.example.libManage.RunnerTests',
  );
}
